### ISSUE TITLE
It's not clear what does 'unconstrained' mean in concepts snippets

### ISSUE THREAD

**Issue by cos-public** [alandefreitas/moderncpp#2]
// Define concept from conjunction of constraints
    template<typename T> concept SignedNumber = Number<T> && std::is_signed_v<T>;

So you call `Number<T>` a constraint.

    // Unconstrained function
    template<Number T>
    void max_value(T a, T b) {
        //...
    }

Which is probably an example of a constrained function for `std::is_arithmetic_v<T>`

**Comment by alandefreitas** [comment]
True. It was "unconstrained" relative to `template<SignedNumber T>` but it doesn't really make sense. A better comment would be something like `Number which is not SignedNumber` or something like that. Or maybe just removing the comment might be a better idea.
